export let sillyPhrases=[
    "La fortuna ti seguirà ovunque, specialmente quando hai bisogno di trovare le chiavi",
    "Le sfide sono come i biscotti: meglio affrontarle con una tazza di caffè in mano",
    "La creatività è come un gatto: a volte scompare, ma alla fine ritorna sempre",
    "Non temere l'ignoto, potrebbe nascondere la tua calza mancante da lavanderia",
    "La gentilezza è la ciliegina sulla torta della vita, anche se preferiresti una torta al cioccolato",
    "I sogni sono come gli avanzi di pizza, meglio condividerli con gli amici",
    "L'amore è come il Wi-Fi: a volte debole, ma quando funziona è fantastico",
    "Ogni fine è un nuovo inizio, soprattutto quando si tratta di una confezione di patatine.,
    "Sii come una stella cadente: breve, luminosa e a volte completamente imprevedibile",
    "La tua resilienza è come un supereroe in pigiama: discreta ma incredibilmente potente",

    "Abbraccia il caos; anche gli spaghetti si sporcano prima di diventare deliziosi",
    "Attento ai pinguini che ballano, potrebbero insegnarti i passi segreti della vita",
    "Ballare come se nessuno stesse guardando, soprattutto se sei in un supermercato",
    "In un mondo pieno di mele, osa essere un ananas. Stai in piedi e indossa la tua corona",
    "La fabbrica dei biscotti della fortuna ha chiamato: vogliono la loro saggezza indietro, ma tu la conservi per le risate",
    "Quando la vita ti dà limoni, prepara una vasca di limonata e invita gli unicorni",
	
    "Se ridere è la migliore medicina, le tue battute sono il rimedio universale",
    "Attenzione alle lumache filosofiche; potrebbero darti consigli esistenziali lenti ma profondi",
    "Indossa calzini spaiati: sono l'arma segreta contro la monotonia",
    "Non sei in ritardo; sei semplicemente in ritardo con stile per la festa cosmica",
    "Cerca saggezza dai panda; hanno padroneggiato l'arte del riposino zen",
    "Quando la luna ti fa l'occhiolino, è il segnale per inventare una nuova mossa di danza",
  
    "Preparati a ricevere regali inaspettati: Babbo Natale è un maestro nell'arte della sorpresa",
    "Gli elfi del Polo Nord dicono che il miglior modo per scaldarsi è ballare la tarantella con i pinguini",
    "Quest'anno il tuo albero di Natale desidera una vacanza esotica sotto i tropici. Considera seriamente la richiesta",
    "Il pupazzo di neve sul tuo vialetto sta studiando filosofia. Domandagli il senso della vita la prossima volta che lo incontri",
    "L'Uomo delle Nevi ha chiesto un cambio di look. Potrebbe apparire in spiaggia con costume da bagno quest'anno",
    "Il Grinch si è iscritto a un corso di cucina per imparare a preparare biscotti migliori. Buona fortuna a mangiare i suoi esperimenti",
    "Le renne stanno pianificando uno sciopero per ottenere più vacanze. Sembra che Rudolph voglia un tour mondiale di celebrità",
    "Il calendario dell'Avvento predice incontri con gnomi che ti insegnano a fare trucchi di magia con bastoncini di zucchero",
    "Babbo Natale ha deciso di modernizzarsi: ora consegna i regali con droni volanti. Sorprendentemente veloci!",
    "Il Polo Nord si sta sciogliendo, e gli elfi stanno aprendo un parco a tema tropicale. Considera una vacanza natalizia sotto palme"
  ]
