export let sillyPhrases=[
	"ciao bischero1",
	"hello bischer2",
	"bonjour bisquer3",
  "ciao bischero4",
	"hello bischer5",
	"bonjour bisquer6",
  "ciao bischero7",
	"hello bischer8",
	"bonjour bisquer9",
  "ciao bischero10",
	"hello bischer11",
	"bonjour bisquer12",
  "ciao bischero13",
	"hello bischer14",
	"bonjour bisquer15",
  "ciao bischero16",
	"hello bischer17",
	"bonjour bisquer18",
	"hello bischer19",
	"bonjour bisquer20",
]